language: java
dist: trusty
jdk:
  - openjdk8
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Yfyp8zFDt/L9KD+rGWXdxkhlhVS5xnTJv36jVcE9VY46lKA5SHH+65PzkWvDDojVSqbsdQ3m2lwbVJUUhQjW2PZuXKI3Pqp6Xphuhy7pVZPHcKd/l+s0Vm2dMujgXm4G9AO8CEGpyT7XlUrAESLZXgK8Bjz0EgZooi9a8BzCsC0CWK5dndTaMzNcSogCnzWHTJLcEJbYzuUVPtIxN3ie778m1C/BTcnnFLNaEwEP5FRHxf6+rzwHw166DxcGr6+RuJJvkD3UPZtRmzjV8l6n92/dtTtKcJ6UXOEvxuCxeEVDmA5PXLJJiMndEBW4rlXXd7K5f/omejPGXHd+WfyQJKG5rDKPooyknwGIwAdvrQbmKQrKllB0eW+OPalXY5jS2iWflhcgxowYN+djeP/YNipl1oGd64zfI8KVMyv1hSzCfs4C8UmEnWdcikdS3xQUpghq/amX4ojsZITrcv0mYbf3aXPMeA5lxBToSMVcyiorji/UfJOl8BZRc/zQZzcs9Rj/Is9Iu1f8mVGoW2+1JSK23cSgK3fXIxEO0A2f6imxapIlxn73n/b+tf6lSS2ip02J1z+Pv5YYksteeUUQJD6IJ7D380Ftc7gWRt6rFKn9x7wKoXFJVBqrrgqUAVF93HN2Ec8Pc0AHxSZArhU6sXxjrIhMHAL2zJD26GkS0+s=
  file: plugin/target/*.jar
  on:
    tags: true